org: js2023
app: webshop
service: webshop

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-north-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    userss:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    products:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: userID-index
            KeySchema:
              - AttributeName: userID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
